config/routes.rb
Epoch::Application.routes.draw do
  get "registrations/create"

  resources :authentications, :posts, :schedules

  devise_for :users,
    path_names: {
      sign_in: "login",
      sign_out: "logout",
    },
    controllers: {
      omniauth_callbacks: "authentications",
      registrations: "registrations"
    }

  root :to => 'home#index'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid, :token, :token_secret, :token_expiry

  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :consumed, :date_added, :date_posted, :user_id

  belongs_to :user
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :basedate, :repeat_type, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :authentications
  has_many :posts
  has_many :schedules

  def apply_omniauth(omni)
    authentications.build(provider: omni['provider'],
                         uid: omni['uid'],
                         token: omni['credentials'].token,
                         token_secret: omni['credentials'].secret)
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def index
    @authentications = current_user.authentications.all
  end

  def logged_in(authentication)
    flash[:notice] = "Logged in Successfully"
    sign_in_and_redirect User.find(authentication.user_id)
  end

  def link(token, token_secret, token_expiry)
    omni = request.env["omniauth.auth"]

    current_user.authentications.create!(
      provider: omni['provider'],
      uid: omni['uid'],
      token: token,
      token_secret: token_secret,
      token_expiry: token_expiry ? DateTime.strptime(token_expiry.to_s, "%s") : nil
    )

    flash[:notice] = "Authentication successful."
    sign_in_and_redirect current_user
  end

  def facebook
    omni = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(
      omni['provider'],
      omni['uid'])

    if authentication
      logged_in(authentication)
    elsif current_user
      token = omni["credentials"].token
      token_secret = ""
      token_expiry = omni["credentials"].expires ? omni["credentials"].expires_at : nil
      link(token, token_secret, token_expiry)
    else
      user = User.new
      user.email = omni['extra']['raw_info'].email
      
      user.apply_omniauth(omni)
      user.save()
     
      flash[:notice] = "Logged in."
      sign_in_and_redirect User.find(user.id)
    end
  end

  def twitter
    omni = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(
      omni["provider"],
      omni["uid"])

    if authentication
      logged_in(authentication)
    elsif current_user
      puts JSON::dump(omni["credentials"])
      token = omni["credentials"].token
      token_expiry = nil
      token_secret = omni["credentials"].secret
      link(token, token_secret, token_expiry)
    else
      session[:omniauth] = omni.except('extra')
      redirect_to new_user_registration_path
    end
  end

  def destroy
    @authentication = Authentication.find(params[:id])
    @authentication.destroy
    redirect_to authentications_url, :notice => "Successfully destroyed authentication."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = current_user.posts.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end

  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end

end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  def index 
    @schedules = current_user.schedules.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/authentications/index.html.erb
<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
    <th>Expiration date</th>
    <th>Actions</th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td><%= authentication.user_id %></td>
      <td><%= authentication.provider %></td>
      <td><%= authentication.uid %></td>
      <td><%= authentication.token_expiry %></td>
      <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "Add Facebook", user_omniauth_authorize_path(:facebook) %> |
  <%= link_to "Add Twitter", user_omniauth_authorize_path(:twitter) %>
</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header_menu.html.erb
<div id="header-menu">
  <%# Show dropdown menu for user controls, if they are signed in %>
  <ul class="cf">
  <li class="about-us"><a href="#">About Us</a></li>
  <li class="help-center"><a href="#">Help Center</a></li>
  <% if user_signed_in? %>
    <li class="dropdown"><a href="#">My Account</a>
      <ul>
        <li class="edit-profile"><%= link_to "Edit profile", edit_user_registration_path %></li>
        <li class="sign-out"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </li>
  <% end %>
  </ul>
</div> <!-- .user-controls -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Epoch</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="user-controls">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>
      <%= link_to "Edit profile", edit_user_registration_path %> |
      <%= link_to "Authentications", authentications_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "with Facebook", user_omniauth_authorize_path(:facebook) %> or
      <%= link_to "with Twitter", user_omniauth_authorize_path(:twitter) %>
    <% end %>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>